name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - ".devcontainer/**"
      - ".github/**"
      - "templates/**"
      - "**/*.nix"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-nix:
    name: Build and Cache Nix development environment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@v3
      - uses: DeterminateSystems/flake-checker-action@v12
      - run: nix flake check --accept-flake-config --all-systems
      - run: nix build --accept-flake-config .#devShells.x86_64-linux.default
      - run: nix build --accept-flake-config .#homeConfigurations.catnip.activationPackage
      - run: nix build --accept-flake-config .#homeConfigurations.root.activationPackage
      - run: nix build --accept-flake-config .#homeConfigurations.vscode.activationPackage
      - run: nix build --accept-flake-config .#devShells.x86_64-linux.default
        working-directory: templates/clojure
      - run: nix build --accept-flake-config .#devShells.x86_64-linux.default
        working-directory: templates/generic
      - run: nix build --accept-flake-config .#packages.x86_64-linux.catnipContainer.copyToDockerDaemon

  publish-flakehub:
    name: Publish to Flakehub
    needs: build-nix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'no-deploy')
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/flakehub-push@main
        if: ${{ github.event_name != 'pull_request' }}
        id: flakehub-push
        with:
          name: ramblurr/nix-agent-dev
          rolling: true
          visibility: public
          include-output-paths: true

  build-and-push:
    name: Build and Push
    needs: build-nix
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'no-deploy')
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix run --accept-flake-config --keep-going '.#packages.x86_64-linux.catnipContainer.copyToDockerDaemon'

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            suffix=-catnip
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
